version: "3.9"

services:
  db:
    image: postgres:17.0
    restart: no
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-service_pulse_check}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT:-5432}:5432'

  redis:
    image: redis:8.2.1
    restart: no
    container_name: 'redis'
    volumes:
      - redis_data:/data
    ports:
      - '${REDIS_PORT:-6379}:6379'

volumes:
  pgdata:
  redis_data:
