"""replaced status with the boolean is_active and removed ServiceStatus and add timeout_in_seconds

Revision ID: 2b68404d5caf
Revises: 2be59bb2c706
Create Date: 2026-08-28 14:18:45.020697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b68404d5caf'
down_revision = '2be59bb2c706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE services SET is_active = (status = 'ACTIVE')")
    op.alter_column('services', 'is_active', nullable=False)
    op.drop_column('services', 'status')


    op.add_column('services', sa.Column('timeout_in_seconds', sa.Float(), nullable=False, server_default='5.0'))
    # ### end Alembic commands ###


def downgrade():
    op.add_column('services', sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='servicestatus'), autoincrement=False, nullable=True))
    op.execute("UPDATE services SET status = CASE WHEN is_active THEN 'ACTIVE' ELSE 'INACTIVE' END")
    op.alter_column('services', 'status', nullable=False)

    op.drop_column('services', 'timeout_in_seconds')
    op.drop_column('services', 'is_active')
