"""add interval_in_second to the service model

Revision ID: 9941521cc3b1
Revises: cab98c47055f
Create Date: 2026-08-26 22:03:57.952039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9941521cc3b1'
down_revision = 'cab98c47055f'
branch_labels = None
depends_on = None

def upgrade():
    op.add_column('services', sa.Column('interval_in_seconds', sa.Integer(), nullable=True))
    op.execute("UPDATE services SET interval_in_seconds = 60 WHERE interval_in_seconds IS NULL")
    op.alter_column('services', 'interval_in_seconds', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'interval_in_seconds')
    # ### end Alembic commands ###
